blank_issues_enabled: false
contact_links:
    - name: Contact the Author
      url: mailto:ayane@duck.com
      about: If you have inquiries that needs to be discussed directly to the author, send them an email.